### PR TITLE
Add initial draft of CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by MoriTanosuke**
Provides a starting ground for #31

Most of the information is taken from [nayafias CONTRIBUTING-template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md), but I tried to incorporate some of the information from the README too.

Github itself has more information about how to set up the project to help new people to contribute to the project, maybe you want to incorporate some of the tips from https://help.github.com/articles/helping-people-contribute-to-your-project/ too.

@therajanmaurya Do you think I missed something important?

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@MoriTanosuke Guidelines looks good. Thanks for sending PR 🙂

**Comment by therajanmaurya** [comment]
One thing needs to add, Add this Contribution guideline link in README, So everyone can get it quickly 🙂.

**Comment by MoriTanosuke** [comment]
I added a link to CONTRIBUTING.md in the README.md. The link points to the *master* branch, so it should work after merging the PR.

@therajanmaurya Please have a look at the README. I added a new section right below the requirements list and before the architecture overview. Seems like a good place for it, or should I move it somewhere else?

**Comment by therajanmaurya** [comment]
No It's good place, Good work 👍

**Pull request merged**
